#ifndef __CONSTANTES_H__
#define __CONSTANTES_H__

#define GRUÑON 'G'
#define DORMILÓN 'D'
#define SABIO 'S'
#define FELIZ 'F'
#define VIDA_TOMATE 30
#define VIDA_ZANAHORIA 25
#define VIDA_BROCOLI 20
#define VIDA_LECHUGA 15
#define VALOR_SEMILLA_TOMATE 5
#define VALOR_SEMILLA_ZANAHORIA 10
#define VALOR_SEMILLA_BROCOLI 15
#define VALOR_SEMILLA_LECHUGA 20
#define VALOR_TOMATE 30
#define VALOR_ZANAHORIA 50
#define VALOR_BROCOLI 70
#define VALOR_LECHUGA 80
#define MOVIMIENTOS_TOMATE_CRECIDO 20
#define MOVIMIENTOS_ZANAHORIA_CRECIDO 15
#define MOVIMIENTOS_BROCOLI_CRECIDO 10
#define MOVIMIENTOS_LECHUGA_CRECIDO 10
#define MOVIMIENTOS_PROPAGAR_PLAGA 10
#define MOVER_ARRIBA 'W'
#define MOVER_IZQUIERDA 'A'
#define MOVER_ABAJO 'S'
#define MOVER_DERECHA 'D'
#define BLANCANIEVES 'S'
#define CULTIVO_VACIO 'C'
#define DEPOSITO 'D'
#define ESPINAS 'E'
#define PLAGAS 'P'
#define FERTILIZANTE 'F'
#define INSECTICIDA 'I'
#define TOMATE 'T'
#define TOMATE_INMADURO 't'
#define ZANAHORIA 'Z'
#define ZANAHORIA_INMADURA 'z'
#define BROCOLI 'B'
#define BROCOLI_INMADURO 'b'
#define LECHUGA 'L'
#define LECHUGA_INMADURA 'l'
#define MAXIMO_MONEDAS 1000
#define MONEDAS_INICIALES_GRUÑON 150 
#define MONEDAS_INICIALES_DORMILON 200
#define MONEDAS_INICIALES_SABIO 250
#define MONEDAS_INICIALES_FELIZ 300
#define MAX_FIL_TERRENO 20
#define MAX_COL_TERRENO 20
#define INCECTICIDAS_INICIALES 3
#define MONEDAS_PINCHASO 5
#define TOPE_ESPINAS 5
#define TOPE_CANASTA 6


#endif /* __CONSTANTES_H__ */